### ISSUE TITLE
Error:  + aSource + '" is not in the SourceMap.

### ISSUE THREAD

**Issue by digisavvy** [floridoo/gulp-sourcemaps#108]
I'm using gulp-sass and just a "few" other packages. I get this error when trying to use gulp-sourcemaps. I run gulp and my styles task errors out. I tried disabling autoprefixer and that doesn't work. As for the note about prefixer.scss not being in the sourcemap that's odd, because the file is present, I'm just not clear on exactly what's going on and hoping someone can shed some light here for me. As far as I know everything that should be there is there...

Thanks. =) 

Error after running gulp:
```
/Users/Alex/Documents/Websites/somelikeitneat.dev/wp-content/themes/somelikeitneat/node_modules/gulp-minify-css/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-consumer.js:415
      throw new Error('"' + aSource + '" is not in the SourceMap.');
            ^
Error: "/bower_components/bourbon/app/assets/stylesheets/addons/_prefixer.scss" is not in the SourceMap.
  at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/Users/Alex/Documents/Websites/somelikeitneat.dev/wp-content/themes/somelikeitneat/node_modules/gulp-minify-css/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-consumer.js:415:13)
  at SourceMapGenerator.<anonymous> (/Users/Alex/Documents/Websites/somelikeitneat.dev/wp-content/themes/somelikeitneat/node_modules/gulp-minify-css/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-generator.js:233:42)
```

Packages:
```
    "browser-sync": "^2.4.0",
    "gulp": "^3.8.11",
    "gulp-autoprefixer": "^2.1.0",
    "gulp-cache": "^0.2.8",
    "gulp-coffee": "^2.3.1",
    "gulp-combine-media-queries": "^0.1.0",
    "gulp-concat": "^2.5.2",
    "gulp-consolidate": "^0.1.2",
    "gulp-filter": "^2.0.2",
    "gulp-ignore": "^1.2.1",
    "gulp-imagemin": "^0.6.2",
    "gulp-jshint": "^1.9.4",
    "gulp-livereload": "^2.1.1",
    "gulp-load-plugins": "^0.6.0",
    "gulp-minify-css": "^0.3.13",
    "gulp-newer": "^0.3.0",
    "gulp-notify": "^2.2.0",
    "gulp-phpcs": "^0.4.0",
    "gulp-plumber": "^0.6.6",
    "gulp-rename": "^1.2.0",
    "gulp-rimraf": "^0.1.0",
    "gulp-ruby-sass": "^1.0.1",
    "gulp-run-sequence": "^0.3.2",
    "gulp-sass": "^1.3.3",
    "gulp-sourcemaps": "^1.5.1",
    "gulp-swig": "^0.7.4",
    "gulp-uglify": "^0.3.2",
    "gulp-util": "^3.0.4",
    "gulp-wp-rev": "0.0.1",
    "gulp-zip": "^2.0.3",
    "swig": "^1.4.2"
```
Task:
```
gulp.task('styles', function () {
	return gulp.src([source+'sass/**/*.scss'])
		.pipe(plumber())
		.pipe(sourcemaps.init())
			.pipe(sass({
				// outputStyle: 'compressed',
				outputStyle: 'nested',
				precision: 10
			}))
		.pipe(sourcemaps.write({includeContent: false}))
		.pipe(sourcemaps.init({loadMaps: true}))
		.pipe(autoprefixer('last 2 version', 'safari 5', 'ie 8', 'ie 9', 'opera 12.1', 'ios 6', 'android 4'))
		.pipe(sourcemaps.write('/sourcemaps'))
		.pipe(plumber.stop())
		.pipe(gulp.dest(source+'css'))
		.pipe(filter('**/*.css')) // Filtering stream to only css files
		.pipe(cmq()) // Combines Media Queries
		.pipe(reload({stream:true})) // Inject Styles when style file is created
		.pipe(rename({ suffix: '-min' }))
		.pipe(minifycss({keepBreaks:true}))
		.pipe(minifycss({ keepSpecialComments: 0 }))
		.pipe(gulp.dest(source+'css'))
		.pipe(reload({stream:true})) // Inject Styles when min style file is created
		.pipe(notify({ message: 'Styles task complete', onLast: true }))
});
```

**Comment by floridoo** [comment]
According to the path
_[...]/node_modules/**gulp-minify-css**/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-consumer.js_
the error happens in `gulp-minify-css`.

**Comment by digisavvy** [comment]
Thanks for the reply. I saw that, too. I went ahead and updated the package I had and still not working. But it is an issue with gulp-minifycss; I replaced it with gulp-uglifycss and it's working just fine now. I can open an issue with the gulpminify css folk.
