### ISSUE TITLE
Sourcemap conflict with Susy

### ISSUE THREAD

**Issue by Tibicenas** [floridoo/gulp-sourcemaps#144]
Check my example repo with the error case:

https://github.com/Tibicenas/gulp-susy_scss

RIght now the example in the repo crash, 

``` shell
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: "/bower_components/susy/sass/susy/output/support/_rem.scss" is not in the SourceMap.
```

but If i  comment in gulp file the three lines about source maps everything works and
on the other hand,  if i comment the susy import in /scss/layouts/grid.scss    everything works too

So, its some conflict between Susy and Sourcemaps.

**Comment by mmikkel** [comment]
+1

**Comment by rodrigoteobaldo** [comment]
+1

**Comment by diegorodriguesvieira** [comment]
+1

**Comment by xstortionist** [comment]
+1

**Comment by geekyMoa** [comment]
+1

**Comment by mike-lighthouse** [comment]
Conflict between Foundation 6 and Sourcemaps too !

**Comment by xstortionist** [comment]
+1

**Comment by superfunkminister** [comment]
+1

**Comment by mistergraphx** [comment]
+1

**Comment by antonmaju** [comment]
+1

**Comment by CalumBaines** [comment]
Just came across this issue, if you replace sourcemaps.write with this in your gulp file it should ignore the @import. Changing sourceroot depending on your project. 

`.pipe(sourcemaps.write({includeContent: false, sourceRoot: '/app'}))`

see 'write options' here for more details: https://github.com/floridoo/gulp-sourcemaps

**Comment by xstortionist** [comment]
@CalumBaines thanks, I'll give it a shot here in a few and let you know.

**Comment by xstortionist** [comment]
@CalumBaines this doesn't work, even though the error is no longer displayed, the sourcemap not showing correct stylesheets now.

**Comment by nmccready** [comment]
This issue is old, but I did manage to get your repo working again with quite of few bugs in it . I targeted it against 1.9.1 and got.

```
╰─⠠⠵ gulp
[01:15:30] Using gulpfile ~/code/github/thirdparties/gulp-susy_scss/gulpfile.js
[01:15:30] Starting 'sass'...
[01:15:30] Starting 'watch'...
[01:15:30] Finished 'watch' after 36 ms

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Unsupported source map encoding charset=utf8;base64
    at PreviousMap.decodeInline (/Users/nem/code/github/thirdparties/gulp-susy_scss/node_modules/postcss/lib/previous-map.js:69:19)
    at PreviousMap.loadMap (/Users/nem/code/github/thirdparties/gulp-susy_scss/node_modules/postcss/lib/previous-map.js:89:25)
    at new PreviousMap (/Users/nem/code/github/thirdparties/gulp-susy_scss/node_modules/postcss/lib/previous-map.js:31:25)
    at new Input (/Users/nem/code/github/thirdparties/gulp-susy_scss/node_modules/postcss/lib/input.js:39:19)
    at Object.parse [as default] (/Users/nem/code/github/thirdparties/gulp-susy_scss/node_modules/postcss/lib/parse.js:17:17)
    at new LazyResult (/Users/nem/code/github/thirdparties/gulp-susy_scss/node_modules/postcss/lib/lazy-result.js:54:42)
    at Processor.process (/Users/nem/code/github/thirdparties/gulp-susy_scss/node_modules/postcss/lib/processor.js:30:16)
    at DestroyableTransform._transform (/Users/nem/code/github/thirdparties/gulp-susy_scss/node_modules/gulp-autoprefixer/index.js:24:5)
    at DestroyableTransform.Transform._read (/Users/nem/code/github/thirdparties/gulp-susy_scss/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/nem/code/github/thirdparties/gulp-susy_scss/node_modules/readable-stream/lib/_stream_transform.js:172:12)
```

**Comment by phated** [comment]
Closing this because that project looks dead (last commit in Aug 2015)
