### ISSUE TITLE
Source maps not showing up in console on google chrome

### ISSUE THREAD

**Issue by zwhitchcox** [floridoo/gulp-sourcemaps#158]
Not sure if this is how this is supposed to work, but I expected errors in Google chrome to take me to the source file, not to the minified file.

This is my gulp file.

```js
gulp.task('scripts', ['clean'], ()=> {
  return gulp
    .src(paths.scripts)
    .pipe(sourcemaps.init())
    .pipe(uglify())
    .pipe(concat('app.min.js'))
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('build'))
})
```

and this is the error I get in the console

```
angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: State ''' is already defined
    at q (https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.15/angular-ui-router.min.js:7:13890)
    at v.u [as state] (https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.15/angular-ui-router.min.js:7:14817)
    at t (http://45.55.253.184:4000/app.min.js:7:29)
    at Object.invoke (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:4450:17)
    at runInvokeQueue (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:4356:35)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:4365:11
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:336:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:4346:5)
    at createInjector (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:4272:11)
    at doBootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js:1630:20)
http://errors.angularjs.org/1.4.3/$injector/modulerr?p0=app&p1=Error%3A%20S….googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.3%2Fangular.js%3A1630%3A20)
```

You can see that this takes you to the minified file (app.min.js:7:29)

**Comment by zwhitchcox** [comment]
Fixed...didn't actually write the sourcemaps...new code:

```js
gulp.task('scripts', ['clean'], ()=> {
  return gulp
    .src(paths.scripts)
    .pipe(sourcemaps.init({
      loadMaps:true
    }))
      .pipe(uglify())
      .on('error',gutil.log)
      .pipe(concat('app.min.js'))
      .pipe(sourcemaps.write('build/sourcemaps'))
    .pipe(gulp.dest('build'))
})
```
