### ISSUE TITLE
Latest update results in: Cannot read property 'constructor' of undefined with angularJs project

### ISSUE THREAD

**Issue by SamanthaAdrichem** [floridoo/gulp-sourcemaps#232]
```
/home/httpd/vhosts/amy-468.my.daisycon.com/node_modules/gulp-sourcemaps/index.js:156
              } else if (ast[key].constructor === Array) {
                                 ^
TypeError: Cannot read property 'constructor' of undefined
    at registerTokens (/home/httpd/vhosts/amy-468.my.daisycon.com/node_modules/gulp-sourcemaps/index.js:156:34)
    at registerTokens (/home/httpd/vhosts/amy-468.my.daisycon.com/node_modules/gulp-sourcemaps/index.js:158:19)
    at registerTokens (/home/httpd/vhosts/amy-468.my.daisycon.com/node_modules/gulp-sourcemaps/index.js:155:17)
    at DestroyableTransform.sourceMapInit [as _transform] (/home/httpd/vhosts/amy-468.my.daisycon.com/node_modules/gulp-sourcemaps/index.js:164:9)
    at DestroyableTransform.Transform._read (/home/httpd/vhosts/amy-468.my.daisycon.com/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/httpd/vhosts/amy-468.my.daisycon.com/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/httpd/vhosts/amy-468.my.daisycon.com/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/home/httpd/vhosts/amy-468.my.daisycon.com/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/home/httpd/vhosts/amy-468.my.daisycon.com/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at write (/home/httpd/vhosts/amy-468.my.daisycon.com/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)

```

**Comment by hummal** [comment]
same here

**Comment by shinnn** [comment]
I don't know whether it can solve the problem or not, `ast[key].constructor === Array` can be rewritten with `Array.isArray(ast[key])` since Node.js supports all ES5 features.

**Comment by nmccready** [comment]
> Array.isArray way avoids Cannot read property 'constructor' of undefined error, at least.

@SamanthaAdrichem or @hummal can you hack the node_module/gulp-sourcemaps to confirm @shinnn 's potential fix. It would be nice to confirm this.

**Comment by hummal** [comment]
He is right. As of the latest node.js version you could easily use even ES6 features without trouble :)
Version: 2.0.0 -> confirmed working
Version: 1.7.1 -> confirmed working

**Comment by nmccready** [comment]
I did test the `Array.isArray` and the specs result in the same. `Array.isArray` is much better anyhow.

**Comment by nmccready** [comment]
I think is resolved. If there is a prob with 2.0.1 or 1.7.2 then we can re-open
