### ISSUE TITLE
Bug in deploy Revert to version ^1.6 to 1.6 in package.json

### ISSUE THREAD

**Issue by nicodmf** [floridoo/gulp-sourcemaps#238]
Hello,

I have one error on deployement. The revert in version 1.6 works (i don't test others versions, but tuesday night this worked too).

The error : 

```
  [RuntimeException]                                                                                                           
  Error: Cannot find module './src/init'                                                                                       
      at Function.Module._resolveFilename (module.js:338:15)                                                                   
      at Function.Module._load (module.js:280:25)                                                                              
      at Module.require (module.js:364:17)                                                                                     
      at require (module.js:380:17)                                                                                            
      at Object.<anonymous> (****node_modules/gulp-sourcemaps/in  
  dex.js:4:9)                                                                                                                  
      at Module._compile (module.js:456:26)                                                                                    
      at Object.Module._extensions..js (module.js:474:10)                                                                      
      at Module.load (module.js:356:32)                                                                                        
      at Function.Module._load (module.js:312:12)                                                                              
      at Module.require (module.js:364:17)  

```

**Comment by remojansen** [comment]
Same issue here 😭 You can see some CI logs at https://travis-ci.org/inversify/InversifyJS/builds/167464412

**Comment by goto-bus-stop** [comment]
2.1.0 is made up of multiple files but only index.js got published:

https://github.com/floridoo/gulp-sourcemaps/blob/master/package.json#L43

**Comment by stevenvachon** [comment]
Getting the same error.

**Comment by nmccready** [comment]
Fun times I'll fix it after the gym.

**Comment by CodeOtter** [comment]
halp my everything is broken :(

**Comment by matthewcpaul** [comment]
Getting `Error: Cannot find module './src/init'` after this latest update as well.

**Comment by Tyriar** [comment]
Same issue

**Comment by nmccready** [comment]
Like I said I'll get to it in a few

**Comment by nmccready** [comment]
For the time being lock your version down to 2.0.x or 1.7.x

**Comment by nmccready** [comment]
93db5f5fd3a05c580b891c41771dc14c1ca585ea

**Comment by nmccready** [comment]
`npm shrinkwrap` also helps as well
