### ISSUE TITLE
Issue upgrading from 1.6 to 2.1 -- Duplicate of #238

### ISSUE THREAD

**Issue by joefeser** [floridoo/gulp-sourcemaps#239]
Our build server fell down right after the release to v2.1.

We got rid of hte ^ to force us back to 1.6 and it all works.

Not sure if this helps.

[15:18:04][Step 2/3] Executing Gulp
[15:18:05][Step 2/3] v6.4.0
[15:18:06][Step 2/3] module.js:457
[15:18:06][Step 2/3]     throw err;
[15:18:06][Step 2/3]     ^
[15:18:06][Step 2/3] 
[15:18:06][Step 2/3] Error: Cannot find module './src/init'
[15:18:06][Step 2/3]     at Function.Module._resolveFilename (module.js:455:15)
[15:18:06][Step 2/3]     at Function.Module._load (module.js:403:25)
[15:18:06][Step 2/3]     at Module.require (module.js:483:17)
[15:18:06][Step 2/3]     at require (internal/module.js:20:19)
[15:18:06][Step 2/3]     at Object.<anonymous> (D:\BuildAgent\work\b82b9fbb18e534b6\node_modules\gulp-sourcemaps\index.js:4:9)
[15:18:06][Step 2/3]     at Module._compile (module.js:556:32)
[15:18:06][Step 2/3]     at Object.Module._extensions..js (module.js:565:10)
[15:18:06][Step 2/3]     at Module.load (module.js:473:32)
[15:18:06][Step 2/3]     at tryModuleLoad (module.js:432:12)
[15:18:06][Step 2/3]     at Function.Module._load (module.js:424:3)

**Comment by dabernathy89** [comment]
This was reported a half hour ago-ish:

https://github.com/floridoo/gulp-sourcemaps/issues/238

**Comment by Lopako** [comment]
Except then the issue was locked, so people couldn't +1 the ticket to inform the devs how massive an impact this bug had.

So now we're waiting until "after the gym"...

**Comment by nmccready** [comment]
Lol I was in my car, such lack of forgiveness

**Comment by dabernathy89** [comment]
@Lopako I'm sure he's aware of the impact. People have lives to live, you can't expect immediate turnaround on open source projects.

**Comment by joefeser** [comment]
Stuff happens @nmccready. It is funny that you pushed and got in the car :). We were scratching our head on how a sql change would break gulp :)

**Comment by lxe** [comment]
Why lock the previous thread? This package was downloaded almost 2 million times in the past months and has countless packages depending on it. The ticket alone can serve as a benchmark and a perspective of the impact gulp-sourcemaps has on the community.

**Comment by Lopako** [comment]
Apologies, didn't mean to come off as such a jerk. =P

And @dabernathy89 - Mistakes happen, stuff breaks. I totally get it, and certainly did not mean to imply I expected any instant "DO OUR BIDDING" turnaround.

I was more remarking on the fact that the locked thread couldn't be thumbs-up'd by people who share the issue. So that others who come a'searching, can feel like their concerns have been noted.
I don't know if github even lets you lock the comments and keep the "thumbs up" still enabled. If possible, that would have been better, IMHO. But if not, I can understand if you were trying to prevent a flood of new comments and posts spam that didn't add anything more than a "me too".

**Comment by nmccready** [comment]
2.1.1 released and 1.8.1

**Comment by dabernathy89** [comment]
Huzzah!

**Comment by nmccready** [comment]
93db5f5fd3a05c580b891c41771dc14c1ca585ea

**Comment by nmccready** [comment]
#238 orig
