### ISSUE TITLE
1.8.0 is broken

### ISSUE THREAD

**Issue by Vanuan** [floridoo/gulp-sourcemaps#241]
Looks like 1.8.0 was published today, which broke things:

```
Error: Cannot find module './src/init'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous>
```

**Comment by Vanuan** [comment]
Duplicate of #238

**Comment by nmccready** [comment]
gracias for closing
