### ISSUE TITLE
Usage with browserify >= 12 gives error

### ISSUE THREAD

**Issue by robations** [floridoo/gulp-sourcemaps#276]
Tested with gulp-sourcemaps 2.4.1.

In combination with browserify 11 all is okay, but 12 and 13 causes an error. Seems possibly related to the comment against version 12 here relating to sourcemaps:

https://github.com/substack/node-browserify/blob/master/changelog.markdown

> Sourcemaps charset now uses an = instead of a :. This fixes certain issues with Chinese characters in sourcemaps. See #753.

Or perhaps it is their change to streams3? I'm not looking under the hood while the engine’s working.

**Comment by nmccready** [comment]
I don't know if this is related. But on the latest / newer versions (12 & 13) of browserify karam would not work as well.

**Comment by robations** [comment]
Additional info. The error is:

```
node_modules/source-map/lib/source-map-generator.js:177
        throw new Error(
        ^

Error: SourceMapGenerator.prototype.applySourceMap requires either an explicit source file, or the source map's "file" property. Both were omitted.
    at SourceMapGenerator_applySourceMap [as applySourceMap] (node_modules/source-map/lib/source-map-generator.js:177:15)
    at SourceMapper.applySourceMap (node_modules/ng-annotate/build/es5/generate-sourcemap.js:92:20)
    at generateSourcemap (node_modules/ng-annotate/build/es5/generate-sourcemap.js:115:20)
    at ngAnnotate (node_modules/ng-annotate/build/es5/ng-annotate-main.js:1221:9)
    at DestroyableTransform.flush [as _flush] (node_modules/browserify-ngannotate/index.js:45:24)
    at DestroyableTransform.<anonymous> (node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at prefinish (node_modules/readable-stream/lib/_stream_writable.js:503:12)
```

Sample invocation:

```
myBrowserifyInstance
            .bundle()
            .pipe(plugins.source("bundle.js"))
            .pipe(plugins.buffer())
            .pipe(plugins.cachebust.resources())
            .pipe(plugins.sourcemaps.init({loadMaps: true}))
            .pipe(plugins.uglify())
            .on("error", plugins.gutil.log)
            .pipe(plugins.sourcemaps.write("./"))
            .pipe(gulp.dest("./dist/js/"))
```

**Comment by phated** [comment]
That stack trace is coming from `ngAnnotate`.  Not a gulp-sourcemap issue.

**Comment by robations** [comment]
Thanks, I'll look at a solution via `ngAnnotate`.
