### ISSUE TITLE
mapSources behave different in Linux with node v6.9.2 and Windows with node  v7.7.1

### ISSUE THREAD

**Issue by dnoliver** [floridoo/gulp-sourcemaps#284]
NOTE: I don't think the the title describe my issue! sorry

I have a Windows machine with node v7.7.1 and a Linux vm with node v6.9.2. I have a typescript project that we compile and append inline sourcemaps using gulp-sourcemaps. To make Visual Studio Code debugger work properly, I had to add a mapSource conversion, here is part of the code

```
gulp.task('compile:typescript', ['clean'], () => (
  tsProject.src()
    .pipe(sourcemaps.init())
    .pipe(tsProject())
    .pipe(sourcemaps.write({
      mapSources: (sourcePath, file) => {
        let converted = sourcePath;

        try {
          const absJsPath = path.dirname(file.path);
          const absTsPath = path.resolve('dist', sourcePath.toString());

          converted = path.relative(absJsPath, absTsPath);
          console.log('sourceMap', sourcePath.toString(), converted);
        } catch (e) {
          console.error(e);
        } finally {
          return converted;
        }
      }
    }))
    .pipe(gulp.dest(paths.tscripts.dest))
));
```

That conversion works in the Linux vm, but i windows throw the following error:

```
Error
    at finish (C:\Users\dnoliver\Git\container-builder\node_modules\run-sequence\index.js:56:13)
    at Gulp.onError (C:\Users\dnoliver\Git\container-builder\node_modules\run-sequence\index.js:67:4)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:191:7)
    at Gulp.Orchestrator._emitTaskDone (C:\Users\dnoliver\Git\container-builder\node_modules\orchestrator\index.js:264:8)
    at C:\Users\dnoliver\Git\container-builder\node_modules\orchestrator\index.js:275:23
    at finish (C:\Users\dnoliver\Git\container-builder\node_modules\orchestrator\lib\runTask.js:21:8)
    at Transform.<anonymous> (C:\Users\dnoliver\Git\container-builder\node_modules\orchestrator\lib\runTask.js:52:4)
    at Transform.f (C:\Users\dnoliver\Git\container-builder\node_modules\end-of-stream\node_modules\once\once.js:17:25)
    at emitOne (events.js:101:20)
    at Transform.emit (events.js:191:7)
    at done (_stream_transform.js:178:19)
    at _stream_transform.js:119:9
    at err (C:\Users\dnoliver\Git\container-builder\node_modules\gulp-eslint\util.js:83:3)
    at Object.exports.tryResultAction (C:\Users\dnoliver\Git\container-builder\node_modules\gulp-eslint\util.js:105:3)
    at Transform.util.transform.done [as _flush] (C:\Users\dnoliver\Git\container-builder\node_modules\gulp-eslint\index.js:125:8)
```

The problem is that sourceMap function is not receiving the same arguments in Linux and Window. On Windows, the second parameter `file` of sourceMap function is 0 instead of a buffer.

Is this a Window issue, or a node version issue?

**Comment by phated** [comment]
This is not a support forum.  Please direct your questions to StackOverflow.  Your error has nothing to do with gulp-sourcemaps because your stack trace indicates your error is coming from gulp-eslint.

**Comment by dnoliver** [comment]
I pasted the wrong stacktrace, sorry!

**Comment by phated** [comment]
There's tons of problems with `tsProject()`.  We aren't supporting it and I'm chalking every issue like this up to that.

**Comment by dnoliver** [comment]
Ok, good to know! thanks @phated
